version: 2
updates:
  - package-ecosystem: bun
    directory: 'packages/cli'
    schedule:
      interval: weekly
    labels:
      - dependencies
    assignees:
      - PunGrumpy
    commit-message:
      prefix: chore
      prefix-development: chore
    versioning-strategy: increase-if-necessary
