name: ğŸ”’ Security

on:
  workflow_call:

env:
  SCOPE_OWNER: '@pungrumpy'

concurrency:
  group: security/${{ github.event.repository.name }}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  gitguardian:
    concurrency:
      group: security/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: ğŸ›¡ï¸ GitGuardian
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v4
      - name: ğŸ›¡ï¸ GitGuardian Scan
        uses: GitGuardian/ggshield-action@v1.27.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
