name: ğŸ”’ Security

on:
  workflow_call:

env:
  SCOPE_OWNER: '@pungrumpy'

concurrency:
  group: security/${{ github.event.repository.name }}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy:
    concurrency:
      group: security/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: ğŸ³ Trivy
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v4
      - name: ğŸ³ Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: .github/trivy.yaml

  snyk:
    concurrency:
      group: security/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    name: ğŸ¶ Snyk
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v4
      - name: ğŸ“¦ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          scope: ${{ env.SCOPE_OWNER }}
      - name: ğŸ¶ Snyk
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: ğŸ¶ Snyk Code Test
        run: snyk code test --sarif > snyk-code.sarif
      - name: ğŸ¶ Snyk Open Source Monitor
        run: snyk monitor --all-projects
      - name: ğŸ†™ Upload Result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
