name: ğŸ”’ Security

on:
  workflow_call:

env:
  SCOPE_OWNER: '@pungrumpy'

concurrency:
  group: security/${{ github.event.repository.name }}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy:
    concurrency:
      group: security/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: ğŸ³ Trivy
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v4
      - name: ğŸ³ Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: .github/trivy.yaml
