name: ğŸ”’ Security

on:
  workflow_call:

env:
  SCOPE_OWNER: '@pungrumpy'

concurrency:
  group: security/${{ github.event.repository.name }}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy:
    concurrency:
      group: security/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: ğŸ³ Trivy
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v4
      - name: ğŸ³ Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: .github/trivy.yaml

  snyk:
    concurrency:
      group: security/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    name: ğŸ¶ Snyk
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v4
      - name: ğŸ¶ Snyk Vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: ğŸ†™ Upload Result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
