name: ğŸ›¡ï¸ Security Scan

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_call:

jobs:
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: ğŸ§‘â€âš•ï¸ CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v6
      - name: ğŸ”¬ Setting up CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript
      - name: ğŸ©» Auto Build
        uses: github/codeql-action/autobuild@v4
      - name: ğŸ§ª Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/languages/javascript-typescript"
