name: ğŸ”’ Security
on:
  workflow_call:
env:
  SCOPRE_OWNER: '@pungrumpy'
concurrency:
  group: security/${{ github.event.repository.name }}
jobs:
  tufflehog:
    concurrency:
      group: security/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: ğŸ„ TruffleHog OSS
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v4
      - name: ğŸ· TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
  trivy:
    concurrency:
      group: security/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: ğŸ³ Trivy
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›« Checkout Code
        uses: actions/checkout@v4
      - name: ğŸ³ Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: .github/trivy.yaml
